package br.edu.ufcg.genus.exception;

public enum ExceptionCategory {
	EXPIRED_ENTRY_CODE,
	JAVAX_VIOLATION,
	INVALID_CREDENTIALS,
	INVALID_ENTRY_CODE,
	INVALID_ID,
	PERMISSION_DENIED,
	INVALID_TOKEN,
	USER_ALREADY_IN_INSTITUTION

}
